name: "lego-up"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

trainer:
  max_steps: 8
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 1
  enable_progress_bar: true
  precision: 32

data_type: "4dgs-multi-view-sample-once-datamodule"
data:
  height: 320
  width: 512
  num_frames: 8
  eval_frames: 8
  eval_height: 640
  eval_width: 1024
  test_height: 1080
  test_width: 1920
  test_extension: 1.0

  azimuth_range: [ -150., 150. ]
  elevation_range: [ -10., 10. ]
  distance_range: [ -0.1, 0.1 ]
  std_azimuth: 0.05
  std_elevation: 0.05
  std_distance: 0.01
  fovx_range: [ 60, 60 ]
  fovy_range: [ 40, 40 ]
  eval_fovx_deg: 60
  eval_fovy_deg: 40
  eval_radius: 0.2

  camera_up: [ 0., 0., 1. ]
  camera_lookat: [ -0.0649, -0.0511, -0.0633 ]
  anchor_view: [ 0.27, 1.53, 0.55 ]

  num_views_per_direction: 10
  num_optimization_steps_before_resampling: 0
  random_views: False

system_type: "gauss-trajectory-4d-system"
system:
  debug: true
  geometry_type: "gaussian-splatting-trajectories"
  back_ground_color: [ 1.0, 1.0, 1.0 ]
  last_step_rigid: True
  geometry:
    sh_degree: 0
    geometry_convert_from: "custom/gaussians2life/assets/sample_data/kitchenlego.ply"
    num_frames: ${data.num_frames}
    update_scale: False
    update_rotation: True
    num_nearest_neighbors: 70
    anchor_view_multiplier: 2
    num_nearest_neighbors_inference: 200
    knn_weighting: 0.0

    mask_box: [ [ -1.0491, 1.4259, 2.0784 ],[ -0.4617, 2.5713, 0.6840 ],[ -0.2292, 1.2610, 2.2884 ],[ -1.0424, 0.6289, 1.4265 ],[ 0.3649, 1.6094, 0.2421 ],[ -0.2225, 0.4640, 1.6365 ],[ -0.4550, 1.7743, 0.0321 ],[ 0.3583, 2.4064, 0.8940 ] ]
    box_rot_x: 90

    inference_mode: "displacement"

  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "solid-color-background" # unused

  renderer_type: "diff-gaussian-rasterizer-dynamic"
  renderer:
    debug: false
    invert_bg_prob: 1.0

  prompt_processor_type: ""
  prompt_processor:
    prompt: ???

  guidance_type: "dynamicrafter-guidance"
  guidance:
    model_config: "custom/gaussians2life/guidance/dynamicrafter/configs/inference_512_v1.0.yaml"
    ckpt_path: "custom/gaussians2life/guidance/dynamicrafter/pretrained_models/dynamicrafter-512.ckpt"
    ddim_steps: 40
    ddim_eta: 1.0
    bs: 1
    width: 512
    height: 320
    num_frames: ${data.num_frames}
    timestep_spacing: uniform
    perframe_ae: True
    frame_stride: 15

    min_step_percent: 0.5
    max_step_percent: 0.75
    guidance_scale: 13
    diffusion_scheduling: "linear"

    anchor_viewpoint_sample_path: "custom/gaussians2life/assets/sample_initial_videos/lego-up.mp4"
    lambda_latent_interpolation: [ 0.6, 0.35 ]
    latent_interpolation_type: "previous"

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

checkpoint:
  save_last: true
  save_top_k: 0 #-1
  every_n_train_steps: ${trainer.max_steps}
